language: node_js
node_js:
 — “8.9.4”
branches:
 only:
  - master
  - develop
before_script:
 — npm install -g ionic cordova
script:
 — ionic cordova build browser — prod
deploy:
 provider: pages
 skip-cleanup: true
 keep-history: true
 on:
   branch: master & develop
 local_dir: www